### ISSUE TITLE
Unable to submit a scene using Maya image sequence files.

### ISSUE THREAD

**Issue by mura-i** [aws-deadline/deadline-cloud-for-maya#204]
### Describe the bug

Scenes using image sequence files cannot be submitted to Deadline Cloud using the usual process. The submitter fails to launch, and an error occurs.

### Expected Behaviour

Using Maya image sequence files allows submission to Deadline Cloud.

### Current Behaviour

Using Maya image sequence files prevents submission to Deadline Cloud.
From its behavior, it seems that the submitter cannot handle loading Maya image sequence files, resulting in an error. 

Currently, when using image sequence files, the submitter can be launched by turning off the image sequence loading first. After the submitter is launched, image sequence loading can be turned back on, allowing the submission to proceed. Rendering works without any issues using this method.

### Reproduction Steps

The file path format for loading image sequences is as follows:

TX_OldPicture01.fff.jpg or TX_OldPicture01.####.jpg

The fff and #### parts represent sequential numbers.

・There are two formats because there are two types of nodes for loading files.
・Maya requires the period (.) before the sequence to properly load the image sequence.

### Environment

At minimum:
1. Operating system: Windows 10 
2. Version of Maya: 2024.5
3. DeadlineCloudMonitor Version:1.1.2
4. If this is from a version installed by the Deadline Cloud Submitter installer, then what version of the submitter installer?
:2024.06.21.0

**Comment by benl-2023** [comment]
Thanks for filing this issue. 

Are you able to provide the exact error produced when the submitter fails to open?

**Comment by mura-i** [comment]
Thank you for your response. Here is the error message.

Error opening the Deadline Cloud Submitter

Exception caught:
Traceback (most recent call last):
File "C:\Users¥DeadlineCloudSubmitter¥Submitters\Maya\scripts\deadline\client\ui\__init__.py", line 38, in
gui_error_handler
yield
File "C:
\Users\DeadlineCloudSubmitter¥Submitters\Maya\scripts\deadline\maya_submitter\mel_commands.py", line 66,
in doIt
DeadlineCloudSubmitterCmd.dialog = show_maya_render_submitter(
File "C:
\Users\DeadlineCloudSubmitter¥Submitters\Maya\scripts\deadline\maya_submitter\maya_render_submitter.py",
line 636, in show_maya_render_submitter
os.path.normpath(path) for path in introspector.parse_scene_assets()
File "C:\Users¥DeadlineCloudSubmitter¥Submitters¥Maya\scripts\deadline\maya_submitter¥assets.py", line 34,
in parse_scene_assets
assets.update(self._get_tx_files())
File "C:\Users¥DeadlineCloudSubmitter¥Submitters\Maya\scripts\deadline\maya_submitter¥assets.py", line 115,
in_get_tx_files
for img_path in self._get_arnold_texture_files():
File "C:\Users¥DeadlineCloudSubmitter¥Submitters\Maya\scripts\deadline\maya_submitter¥assets.py", line 133,
in_get_arnold_texture_files
return mtoa.get_scanned_files(mtoa.scene_default_texture_scan)
File "C:\Program Files\Autodesk\Arnold\maya2024\scripts\mtoa¥txManager\lib.py", line 356, in get_scanned_files
return build_texture_data(textures)
File "C:\Program Files\Autodesk\Arnold¥maya2024\scripts\mtoa¥txManager\lib.py", line 364, in build_texture_data
texture_exp = makeTx.expandFilename With SearchPaths(texture)
File "C:\Program Files\Autodesk Arnold\maya2024\scripts\mtoa¥makeTx.py", line 158, in
expandFilenameWithSearchPaths
if re.match(seq_path_rx, expanded_img):
File "C:\Program Files\Autodesk Maya2024\Python\lib\re.py", line 190, in match
return _compile(pattern, flags).match(string)
File "C:\Program Files\Autodesk Maya2024\Python\lib\re.py", line 303, in _compile
p=sre_compile.compile(pattern, flags)
File "C:\Program Files\Autodesk Maya2024\Python\lib\sre_compile.py", line 788, in compile
p = sre_parse.parse(p, flags)
File "C:\Program Files\Autodesk Maya2024\Python\lib\sre_parse.py", line 955, in parse
p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
File "C:\Program Files\Autodesk Maya2024\Python\lib\sre_parse.py", line 444, in _parse_sub
itemsappend(_parse(source, state, verbose, nested + 1,
File "C:\Program Files\Autodesk Maya2024\Python\lib\sre_parse.py", line 526, in _parse
code = _escape(source, this, state)
File "C:\Program Files\Autodesk Maya2024\Python\lib\sre_parse.py", line 427, in _escape
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \M at position 28



Thank you in advance.

**Comment by jericht** [comment]
Hi @mura-i. This error comes from a call we make to `mtoa` to scan for the texture files used in the scene. It is failing because of a regular expression pattern, which has texture file path in it, has an invalid `\M` sequence in it. All of the file discovery and processing is done within `mtoa`, so I'm not sure the submitter is doing anything to cause the issue.

Just to sanity check, I tried reproducing the error but I've been unsuccessful so far. I have a simple scene that has a cube using a material with an image sequence as its texture, have the frame range set to multiple frames, and I am able to open the submitter. I can also see that the auto detected job attachments in the "Job attachments" tab of the submitter has loaded all of my image sequence files.

For your image sequence files, do any of the file names or file paths have `\M` in them? Are you able to share an example of what one of those file paths might look like?

**Comment by jairaws** [comment]
This issue has been solved in a more recent version of the submitter.
